### ISSUE TITLE
robots.txt not generated + robots.txt fixes

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/OpenClassifieds#2]
http://open-classifieds.com/forums/topic/issue-1-8-2-robots-txt-not-generated-robots-txt-fixes/#post-6795

**Comment by emanwebdev** [comment]
Hi chema

issue closed but can't find the solution/fix?

**Comment by neo22s** [comment]
https://github.com/neo22s/OpenClassifieds/commit/a2d0f09cabf7968aae6346d667b69c1dbd522644

same one I had problems commenting the issues at the beginning.
