### ISSUE TITLE
[SEO] improve path of stored pictures

### ISSUE THREAD

**Issue by emanwebdev** [open-classifieds/OpenClassifieds#20]
instead of /yyyy/mm/dd/id.jpg

something more SEO-friendly like 

/pictures/category/picture-slug.jpg

? or ?

/pictures/location/picture-slug.jpg

? or ?

/pictures/category/location/picture-slug.jpg

? or ?

/pictures/location/category/picture-slug.jpg

Which one is better?
In what case?
etc...

**Comment by neo22s** [comment]
better for oc 2.0.

Not sure if this has really a SEO effect we should consult some expert I guess.

**Comment by jmdoren** [comment]
I run a hughe site with classifieds and a lot of users came searching for
images, a good idea is to use images like this

<img src="/images/category-name/red-women-shoes-id.jpg" alt="red women
shoes" title="red women shoes" width="...

2012/11/28 Chema notifications@github.com

> better for oc 2.0.
> 
> Not sure if this has really a SEO effect we should consult some expert I
> guess.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/neo22s/OpenClassifieds/issues/20#issuecomment-10802756.

## 

Juan Manuel Doren
Santiago, Chile

**Comment by emanwebdev** [comment]
I strongly confirm (I used to be SEO consultant from 2008 to 2011)

**Especially for a classifieds ads website where the text is _sparse_** 
and with only 1 main  picture (right, can have more but...)

It's why KeyWords used in the URL of the image re inforce the relevance / adequacy of 
the KeyWords found in the `<title>`, `<h1>`, `<hx>` and the description of the ad (aka the text)

> I run a hughe site with classifieds and a lot of users came searching for
> images, a good idea is to use images like this

right. And these are Google recommandations as well

P.S.
the name of the pic is already SEO-friendly :

`$file_name = friendly_url($title).'_'.$i.strtolower(substr($file_name, strrpos($file_name, '.')));`

but $file_name could have been renamed instead of using the original name from the $_POST

**Comment by emanwebdev** [comment]
P.S.
I already implement that functionnality in a strongly customized version based upon v.1.7.6

it involved quite a lot of changes due to the 
`function getPostImages($idPost,$date,...)` based of the DATE of the post!!!

it was a good opportunity to improve that function as it was an extensive(?) call to `scandir()` in it

Same story regarding the `function upload_images_form` that needed a $date to store the picture(s)

P.S.
If I could "connect" to this GitHub repository, I'd be pleased to send you Pull Requests.
There are dozen in the pipeline ;)

**Comment by emanwebdev** [comment]
_Starting to implement it_

_but_ ...

facing BACKWARD compatibility issues!!!

What to do with pictures already uploaded?

**Comment by neo22s** [comment]
Hello,

we are working on 2.0. I tihnk we are going to freeze 1.8.3. unless bugs are found.

So no more development for OC 1.8.X version and we are going to focus 100% on newest version.

Regards

**Comment by emanwebdev** [comment]
Hola

> we are working on 2.0

Why to rewrite all? 
Will performance be better with a framework?
And memory footprint?
aso...

Right, maintenance should be easier

**Comment by neo22s** [comment]
maintenance...and next features easier to develop...I hate the current code goes against my engineering principles.

On monday a Slobodan (I hired him) is going to start working only for this and I am going to do as much as possible also, so any help would be awesome!

regards.

**Comment by emanwebdev** [comment]
> a Slobodan 

?

do you mean a Serbian?

or a free developer?

**Comment by emanwebdev** [comment]
> I hate the current code goes against my engineering principles.

I too...

VERY messy, 

TOO easy to break

aso...

but the good thing is it's fast and with a Very light memory footprint
Important for high traffic websites IMHO, even if there are numerous ways nowadays 
to improve the pages load time of a website

Btw, I don't understand why query cache does not work,
I will check it later

**Comment by neo22s** [comment]
Hello,

He is an employee I hired, starting on monday in my offices in Barcelona ;)

Kohana works great on high traffic sites I guarantee you! :dancer:

**Comment by emanwebdev** [comment]
> He is an employee I hired

good! (i read that on the blog of OC http://open-classifieds.com/2012/11/28/last-days-for-lite-edition/ )

> Kohana works great on high traffic sites

good news
will you make it Open Source as I see you have a repo here: https://github.com/neo22s/openclassifieds2

**Comment by neo22s** [comment]
yes!! we love open source :D
