### ISSUE TITLE
[STATS] totalAds issue

### ISSUE THREAD

**Issue by emanwebdev** [open-classifieds/OpenClassifieds#24]
totalAds issue when category AND a number of days are specified 

Fixed:
https://github.com/neo22s/OpenClassifieds/commit/b9eddc218075c3c14b260ae9df9234777c5177e8#includes/menu.php

**Comment by neo22s** [comment]
great! just on time I was going to release 1.8.4. I am going to close the branch now, no more commits please :D

**Comment by emanwebdev** [comment]
- add same issue with totalViews()

**Comment by neo22s** [comment]
got it ;)

**Comment by emanwebdev** [comment]
> I am going to close the branch now

humm..... just a bit too early :calendar:  my friend :v: 

i'm just reviewing the WHOLE code right now 
2 days scheduled for that

**Comment by neo22s** [comment]
woooow

so you want me to wait?
I had scheduled a release for today.

Well I will wait for you. then, please let me know.

Regards

**Comment by neo22s** [comment]
ok, I reeschedule for monday 10th as last day.

Thanks.

**Comment by emanwebdev** [comment]
Up to you, but for sure I'm 100% working on OC 1.8.3+ until... it's done :)

why do you want to hurry to release 1.8.4? i don't see any blog post on the official site?

well, pretty sure there are a couple of fixes that will arise by the end of the week

**Comment by neo22s** [comment]
Please only commit on 1.8.4 branch not the 1.8.3 ;)

Not much hurry, but I made some changes adding more adsense and deleted almost all the themes to make them premium, I need to start getting more revenue from the PRO versions, and I had a schedule fixed to do so, that's all ;).

Also please do a pull as you can see I changed few things.

thanks.

**Comment by emanwebdev** [comment]
> Please only commit on 1.8.4 branch

ok

> the themes (...)

wordcloud CSS issues on almost ALL Premium themes. Double-check the premium themes CSS

> and I had a schedule fixed to do so, that's all ;).

ok, sorry for that. but again, up to you :)

> please do a pull

?  you mean to pull the whole branch 1.8.4 ?

**Comment by neo22s** [comment]
well just update your branch I mean ;)

I will fix the wordcloud, thanks again!

No problem I change the plan and that is all. :dancers:
