### ISSUE TITLE
[INSTALL] Ocacu registration

### ISSUE THREAD

**Issue by emanwebdev** [open-classifieds/OpenClassifieds#29]
> No it was meant to register only if it was successful...that's a bug :( can you fix it? thanks.

it's not about registering if it was successful

it's about "Do you allow people NOT to register on install" ?

is that ok for you to have website running OC without being registered to Ocacu?

As in that case you cannot 
- get noticed of new installations
- nor offer follow-up 
- nor offer new themes

They are 2 different things to record:
- Ocacu registration
- new installation, for the sake of your business :+1:

**Comment by neo22s** [comment]
I know...to be fair you should be able to choose.

I am changing the business already no free forum only 1 free theme...

Let's see if that is enough if not I will create life cycle emails after installation and force them to register at ocaku.

I hope I don't need to but...who knows.

**Comment by emanwebdev** [comment]
>  life cycle emails after installation

so you do **need** to _collect these :e-mail: addresses at install time_

at the end of a successful installation, v.easy to send an :email: to a specific address @Open Classifieds
it's a :key: point for the sake of...

**Comment by neo22s** [comment]
I understand...I was doing that before.

Maybe we could suscribe them to a newsletter...or something like that...

I will think about it, thanks.

**Comment by emanwebdev** [comment]
> suscribe them to a newsletter.

right, but to a **different** newsletter than the official one. One targeted at _converting_ prospects to customers
but right, it's another story, just my marketing side coming back ;)

**Comment by neo22s** [comment]
No its great I mean ;)
