### ISSUE TITLE
OC is not suited to vehicles or housing ads...

### ISSUE THREAD

**Issue by helhamma** [open-classifieds/OpenClassifieds#35]
Hi Chema,

here is a general suggestion for OC 2.

OC 1.8 is suited for most of ads categories but not for Vehicles or Housing ones.

For vehicles ads, a customer would want to search according to specific criterias like kilometers and fuel type. 
Regarding housing ads, a customer would want to search according to other specific criterias like housing type, surface area and number of rooms.

I think this probably means proposing a template when creating categories from admin pages... 

Do you think it's possible?

Holmi

**Comment by neo22s** [comment]
We will see but 2.0. is not going to be developed to cover that so far.

**Comment by helhamma** [comment]
Thanks for the answer.

If you're interested let me know, I have a couple of ideas to do it simple. But of course, this would have impacts on:
- categories table
- posts table
- categories.php
- new-item.php
- item-manage.php
- search.php
- list.php
- item.php

**Comment by neo22s** [comment]
and the DB...

At 2.0. we don't use those files anymore or architecture.

If you want to develop for 2.0. feel welcome,

**Comment by helhamma** [comment]
I would be glad to but I can't see the code anywhere?

**Comment by neo22s** [comment]
It's in my user under another repo:
https://github.com/neo22s/openclassifieds2
