### ISSUE TITLE
Htaccess Terms

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/OpenClassifieds#5]
http://open-classifieds.com/forums/topic/bug-1-8-2-previous/#post-6855

**Comment by emanwebdev** [comment]
where is your commit?

**Comment by neo22s** [comment]
https://github.com/neo22s/OpenClassifieds/commit/a2d0f09cabf7968aae6346d667b69c1dbd522644 

I think is this one, this commit was not properly commented.
