### ISSUE TITLE
Seo speed Improvement

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/OpenClassifieds#6]
http://open-classifieds.com/forums/topic/speed-easy-improvement/

also add the seo title generator, move it form the oc class to the seo class.

**Comment by emanwebdev** [comment]
Hi

where is your commit?

**Comment by neo22s** [comment]
https://github.com/neo22s/OpenClassifieds/commit/cee31e261c8b2d07fad92af87fdfc6bab32429b5

**Comment by neo22s** [comment]
I didn't add it to the admin, I don't think there's need.
