### ISSUE TITLE
Improve moderation

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/OpenClassifieds#8]
multi select

mark as spam

pagination

search duplicated ads??

**Comment by neo22s** [comment]
http://iknowkungfoo.com/blog/index.cfm/2012/4/18/Check-All-Checkboxes-with-jQuery--Revisited
http://www.phpinterviewquestion.com/jquery/check-or-uncheck-all-checkboxes-using-jquery

**Comment by emanwebdev** [comment]
:) Hi Chema  
You are good at finding free solutions

**Comment by neo22s** [comment]
yes! hehehe ;)
